SET HEADING OFF
SET FEEDBACK OFF
SET PAGESIZE 0
SET VERIFY OFF
SET ECHO OFF
SET TERMOUT ON
SET TRIMSPOOL ON
SET LINESIZE 400

SELECT 'CHECK|COURSES|expected=6|actual=' || COUNT(*) || '|status=' || CASE WHEN COUNT(*) = 6 THEN 'OK' ELSE 'FAIL' END FROM COURSES;
SELECT 'CHECK|SKILLS|expected=6|actual=' || COUNT(*) || '|status=' || CASE WHEN COUNT(*) = 6 THEN 'OK' ELSE 'FAIL' END FROM SKILLS;
SELECT 'CHECK|TOPICS|expected=20|actual=' || COUNT(*) || '|status=' || CASE WHEN COUNT(*) = 20 THEN 'OK' ELSE 'FAIL' END FROM TOPICS;
SELECT 'CHECK|SUBTOPICS|expected=50|actual=' || COUNT(*) || '|status=' || CASE WHEN COUNT(*) = 50 THEN 'OK' ELSE 'FAIL' END FROM SUBTOPICS;
SELECT 'CHECK|LEARNING_PATHS|expected=15|actual=' || COUNT(*) || '|status=' || CASE WHEN COUNT(*) = 15 THEN 'OK' ELSE 'FAIL' END FROM LEARNING_PATHS;
SELECT 'CHECK|EVALUATIONS|min=300|actual=' || COUNT(*) || '|status=' || CASE WHEN COUNT(*) >= 300 THEN 'OK' ELSE 'FAIL' END FROM EVALUATIONS;
SELECT 'CHECK|GAPS|min=200|actual=' || COUNT(*) || '|status=' || CASE WHEN COUNT(*) >= 200 THEN 'OK' ELSE 'FAIL' END FROM GAPS;
SELECT 'CHECK|CORE_TOPICS|min=3|actual=' || COUNT(*) || '|status=' || CASE WHEN COUNT(*) = 3 THEN 'OK' ELSE 'FAIL' END FROM TOPICS WHERE NAME IN ('HTML y CSS', 'JavaScript', 'Spring Boot');
SELECT 'CHECK|INACTIVE_TOPICS|min=1|actual=' || COUNT(*) || '|status=' || CASE WHEN COUNT(*) >= 1 THEN 'OK' ELSE 'FAIL' END FROM TOPICS WHERE ACTIVE = 0;
SELECT 'CHECK|SEEDED_STUDENTS|min=5|actual=' || COUNT(DISTINCT STUDENT_ID) || '|status=' || CASE WHEN COUNT(DISTINCT STUDENT_ID) >= 5 THEN 'OK' ELSE 'FAIL' END FROM LEARNING_PATHS;
SELECT 'CHECK|STUDENT_A00835001_PATHS|min=3|actual=' || COUNT(*) || '|status=' || CASE WHEN COUNT(*) >= 3 THEN 'OK' ELSE 'FAIL' END FROM LEARNING_PATHS WHERE STUDENT_ID = 'A00835001';

EXIT;