spring.application.name=api-gateway
server.port=8080
spring.cloud.gateway.enabled=false

spring.cloud.gateway.routes[0].id=session-service
spring.cloud.gateway.routes[0].uri=http://localhost:8086
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/sessions,/api/v1/sessions/**

spring.cloud.gateway.routes[1].id=evaluator-service-evaluations
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/evaluations,/api/v1/evaluations/**

spring.cloud.gateway.routes[2].id=evaluator-service-topics
spring.cloud.gateway.routes[2].uri=http://localhost:8082
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/topics,/api/v1/topics/**

spring.cloud.gateway.routes[3].id=gap-detector-service
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/gaps,/api/v1/gaps/**

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173,http://localhost:5174,http://localhost:5175
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PATCH,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

eureka.client.enabled=false
management.endpoints.web.exposure.include=health,info
