-- Sample data for gap-detector-service (Oracle)
-- NOTE: The canonical seed data is in infrastructure/oracle/V2__seed_data.sql
-- This file is kept as a quick reference for local testing.

-- Courses
INSERT INTO COURSES (ID, NAME, CODE) VALUES (SEQ_COURSES.NEXTVAL, 'Estructura de Datos', 'TC1031');
INSERT INTO COURSES (ID, NAME, CODE) VALUES (SEQ_COURSES.NEXTVAL, 'Base de Datos', 'TC1032');

-- Topics (referencing COURSES by ID)
INSERT INTO TOPICS (ID, NAME, COURSE_ID) VALUES (SEQ_TOPICS.NEXTVAL, 'Recursión', 1);
INSERT INTO TOPICS (ID, NAME, COURSE_ID) VALUES (SEQ_TOPICS.NEXTVAL, 'Árboles Binarios', 1);
INSERT INTO TOPICS (ID, NAME, COURSE_ID) VALUES (SEQ_TOPICS.NEXTVAL, 'SQL Joins', 2);

-- Subtopics
INSERT INTO SUBTOPICS (ID, NAME, TOPIC_ID) VALUES (SEQ_SUBTOPICS.NEXTVAL, 'Recursion Basics', 1);
INSERT INTO SUBTOPICS (ID, NAME, TOPIC_ID) VALUES (SEQ_SUBTOPICS.NEXTVAL, 'Linked List Traversal', 1);
INSERT INTO SUBTOPICS (ID, NAME, TOPIC_ID) VALUES (SEQ_SUBTOPICS.NEXTVAL, 'Binary Tree Balancing', 2);
INSERT INTO SUBTOPICS (ID, NAME, TOPIC_ID) VALUES (SEQ_SUBTOPICS.NEXTVAL, 'SQL Inner Join', 3);
INSERT INTO SUBTOPICS (ID, NAME, TOPIC_ID) VALUES (SEQ_SUBTOPICS.NEXTVAL, 'Normalization', 3);

-- Gaps (now includes TOPIC_ID, CONCEPT, CONFIDENCE)
INSERT INTO GAPS (ID, STUDENT_ID, TOPIC_ID, SUBTOPIC_ID, CONCEPT, SEVERITY, CONFIDENCE, DETECTED_AT, RESOLVED)
VALUES (SEQ_GAPS.NEXTVAL, 'A00835001', 2, 3, 'Balanceo de árboles AVL', 'HIGH', 0.85, TIMESTAMP '2026-02-18 11:45:00', 0);

INSERT INTO GAPS (ID, STUDENT_ID, TOPIC_ID, SUBTOPIC_ID, CONCEPT, SEVERITY, CONFIDENCE, DETECTED_AT, RESOLVED)
VALUES (SEQ_GAPS.NEXTVAL, 'A00835002', 1, 2, 'Recorrido de listas enlazadas', 'MEDIUM', 0.72, TIMESTAMP '2026-02-16 14:15:00', 0);

INSERT INTO GAPS (ID, STUDENT_ID, TOPIC_ID, SUBTOPIC_ID, CONCEPT, SEVERITY, CONFIDENCE, DETECTED_AT, RESOLVED)
VALUES (SEQ_GAPS.NEXTVAL, 'A00835003', 3, 4, 'SQL Inner Join con múltiples tablas', 'LOW', 0.60, TIMESTAMP '2026-02-20 08:00:00', 1);

INSERT INTO GAPS (ID, STUDENT_ID, TOPIC_ID, SUBTOPIC_ID, CONCEPT, SEVERITY, CONFIDENCE, DETECTED_AT, RESOLVED)
VALUES (SEQ_GAPS.NEXTVAL, 'A00835001', 3, 5, 'Formas normales (1NF-3NF)', 'MEDIUM', 0.78, TIMESTAMP '2026-02-21 10:30:00', 0);

INSERT INTO GAPS (ID, STUDENT_ID, TOPIC_ID, SUBTOPIC_ID, CONCEPT, SEVERITY, CONFIDENCE, DETECTED_AT, RESOLVED)
VALUES (SEQ_GAPS.NEXTVAL, 'A00835002', 1, 1, 'Casos base en recursión', 'LOW', 0.55, TIMESTAMP '2026-02-22 13:00:00', 1);
