package com.tutorbot.evaluator.event;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.amqp.rabbit.annotation.RabbitListener;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Component;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.tutorbot.evaluator.dto.EvaluationRequest;
import com.tutorbot.evaluator.dto.EvaluationResponse;
import com.tutorbot.evaluator.service.EvaluationService;

@Component
@ConditionalOnProperty(name = "tutorbot.messaging.enabled", havingValue = "true")
public class EvaluatorEventListener {

    private static final Logger log = LoggerFactory.getLogger(EvaluatorEventListener.class);

    private final EvaluationService evaluationService;
    private final ObjectMapper objectMapper;
    private final EvaluationEventPublisher publisher;

    public EvaluatorEventListener(EvaluationService evaluationService,
            ObjectMapper objectMapper,
            EvaluationEventPublisher publisher) {
        this.evaluationService = evaluationService;
        this.objectMapper = objectMapper;
        this.publisher = publisher;
    }

    @RabbitListener(queues = "${rabbitmq.queues.student-answered}")
    public void onStudentAnswered(String message) {
        try {
            StudentAnsweredEvent event = objectMapper.readValue(message, StudentAnsweredEvent.class);
            log.info("Received student.answered event for student={} session={}",
                    event.studentId(), event.sessionId());

            EvaluationRequest request = new EvaluationRequest(
                    event.sessionId(),
                    event.studentId(),
                    event.questionText(),
                    event.studentAnswer(),
                    event.correctAnswer(),
                    event.maxScore(),
                    event.topicId());

            EvaluationResponse result = evaluationService.evaluate(request);

            // Map EvaluationResponse -> EvaluationCompletedEvent (evaluationId will be generated by publisher if missing)
            var completed = new EvaluationCompletedEvent(
                    null,
                    result.sessionId(),
                    result.studentId(),
                    result.topicId(),
                    result.score(),
                    result.feedbackSummary(),
                    null);

            publisher.publishEvaluationCompleted(completed);

        } catch (Exception e) {
            log.error("Error processing student.answered message='{}' error='{}'", message, e.getMessage(), e);
        }
    }
}
